//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongestionTaxCalculator.ConsoleApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CongestionTaxCalculator.ConsoleApp.Resources.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the vehicle&apos;s license plate: .
        /// </summary>
        internal static string Program_CalculateTotalCongestionTax_EnterLicensePlateMessage {
            get {
                return ResourceManager.GetString("Program_CalculateTotalCongestionTax_EnterLicensePlateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Congestion Tax: {0} SEK.
        /// </summary>
        internal static string Program_CalculateTotalCongestionTax_TotalCongestionTaxOutputMessage {
            get {
                return ResourceManager.GetString("Program_CalculateTotalCongestionTax_TotalCongestionTaxOutputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [2] Calculate total toll fee of a specific data..
        /// </summary>
        internal static string Program_ChooseAnAction_CalculateCongestionTax {
            get {
                return ResourceManager.GetString("Program_ChooseAnAction_CalculateCongestionTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose one of options above: .
        /// </summary>
        internal static string Program_ChooseAnAction_ChooseOneOption {
            get {
                return ResourceManager.GetString("Program_ChooseAnAction_ChooseOneOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1] Insert new data..
        /// </summary>
        internal static string Program_ChooseAnAction_InsertData {
            get {
                return ResourceManager.GetString("Program_ChooseAnAction_InsertData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the program instance..
        /// </summary>
        internal static string ProgramInstanceCreationError {
            get {
                return ResourceManager.GetString("ProgramInstanceCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating the program instance: {0}.
        /// </summary>
        internal static string ProgramInstanceCreationErrorMessageDetails {
            get {
                return ResourceManager.GetString("ProgramInstanceCreationErrorMessageDetails", resourceCulture);
            }
        }
    }
}
